collections:
  - projects

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: "Jort van Leenen"
description: "Jort van Leenen's personal website"
domain: "jortvanleenen.nl"
url: "https://jortvanleenen.nl"
baseurl: ""
author: "Jort van Leenen"
social:
  name: Jort van Leenen
  links:
    - https://www.linkedin.com/in/jortvanleenen
    - https://github.com/jortvanleenen/
lang: en-GB
locale: en_GB
permalink: /:slugified_categories/:year/:month/:day/:slug

exclude:
  - LICENSE
  - README.md

defaults:
  - scope:
      path: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"