collections:
  - projects

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank

title: "Jort van Leenen"
description: "Jort van Leenen's personal website"
domain: "jortvanleenen.nl"
url: "https://jortvanleenen.nl"
baseurl: ""
author: "Jort van Leenen"
email: "jort@vleenen.nl"
social:
  name: Jort van Leenen
  links:
    - https://www.linkedin.com/in/jortvanleenen
    - https://github.com/jortvanleenen/
lang: en-GB
locale: en_GB
permalink: /:categories/:year/:month/:day/:slug

exclude:
  - LICENSE
  - README.md

defaults:
  - scope:
      path: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# jekyll-sass-converter (default in Jekyll gem)
sass:
  style: compressed

# jekyll-target-blank
target-blank:
  add_css_classes: external